#!/bin/sh
# shortcut to recompile both game_state and mod_rendering, in case of working on rendering innards
export RUST_BACKTRACE=1
set -e
cd nom-obj
cargo build
cd ..
cd game_state
cargo build
cd ..
cd mod_rendering
cargo build
cd ..
cargo run

