pub enum GenericSoundID{
    PLASMA_FIRE_SOUNDID = 1,
    EMP_FIRE_SOUNDID,
    CLICK_SOUNDID,
    BOOST_SOUNDID,
    SCAN_SOUNDID,
    SCAN_COMPLETE_SOUNDID,
    PING_SOUNDID,

    SOUNDID_COUNT
}

pub enum LaserType {
    LASER_TYPE,
    EMP_TYPE
}

pub enum DamageType {
    LASER_DAMAGE,
    EMP_DAMAGE,
    COLLISION_DAMAGE
}

pub enum GameStateMode {
    RUNNING_GAMESTATE = 0,
    PAUSED_GAMESTATE,
    JUMPING_IN_GAMESTATE
}
